#!/usr/bin/env python
from ptero_shell_command_fork.api.wsgi import app
import argparse

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--port', type=int, default=5001)
    return parser.parse_args()

if __name__ == '__main__':
    args = parse_args()
    app.run(debug=True, port=args.port)
