#!/usr/bin/env python

from ptero_common.janitors.redis_janitor import RedisJanitor
from ptero_common.janitors.rabbitmq_janitor import RabbitMQJanitor
from ptero_common.janitors.postgres_janitor import PostgresJanitor
from ptero_common.janitors import perform_cleanup
import os


if __name__ == '__main__':
    perform_cleanup(janitor_spec={
        'postgres': {
            'required_envvars': ['PTERO_LSF_DB_STRING'],
            'cleanup_action': lambda: PostgresJanitor(
                os.environ['PTERO_LSF_DB_STRING']).clean(),
            },
        'rabbitmq': {
            'required_envvars': ['PTERO_LSF_CELERY_BROKER_URL'],
            'cleanup_action': lambda: RabbitMQJanitor(
                os.environ['PTERO_LSF_CELERY_BROKER_URL']).clean(),
            },
        'redis': {
            'required_envvars': ['PTERO_LSF_CELERY_RESULT_BACKEND'],
            'cleanup_action': lambda: RedisJanitor(
                os.environ['PTERO_LSF_CELERY_RESULT_BACKEND']).clean(),
            },
        })
