rabbit: RABBITMQ_LOG_BASE=$PWD/$RABBITMQ_LOG_BASE RABBITMQ_MNESIA_BASE=$PWD/$RABBITMQ_MNESIA_BASE rabbitmq-server
redis: redis-server --port $REDIS_PORT
web: python tests/scripts/web_wrapper.py
worker: coverage run $(which celery) worker -n shell_worker.%h.$PORT --pool=eventlet --concurrency 1 -A ptero_shell_command_fork.implementation.celery_app
